import type { NavGroup } from "./types";

export const CONVERT_GROUP: NavGroup = {
	id: "cv",
	label: "Video Conversion",
	items: [
		{
			id: "cv.transcode",
			title: "Transcode",
			icon: "ArrowRightLeft",
			status: "planned",
			items: [
				{
					id: "cv.transcode.quick-convert",
					title: "Quick Convert",
					icon: "Gauge",
					url: "/convert/quick",
					status: "ready",
				},
				{
					id: "cv.transcode.to-container",
					title: "To Container",
					icon: "FileOutput",
					status: "planned",
					items: [
						{
							id: "cv.transcode.to-container.mp4",
							title: "MP4",
							icon: "Box",
							url: "/convert/container/mp4",
							status: "planned",
						},
						{
							id: "cv.transcode.to-container.mkv",
							title: "MKV",
							icon: "Box",
							url: "/convert/container/mkv",
							status: "planned",
						},
						{
							id: "cv.transcode.to-container.mov",
							title: "MOV",
							icon: "Box",
							url: "/convert/container/mov",
							status: "planned",
						},
						{
							id: "cv.transcode.to-container.webm",
							title: "WebM",
							icon: "Box",
							url: "/convert/container/webm",
							status: "planned",
						},
						{
							id: "cv.transcode.to-container.avi",
							title: "AVI",
							icon: "Box",
							url: "/convert/container/avi",
							status: "planned",
						},
					],
				},
				{
					id: "cv.transcode.batch-convert",
					title: "Batch Convert",
					icon: "Layers",
					url: "/convert/batch",
					status: "planned",
				},
			],
		},
		{
			id: "cv.video-codecs",
			title: "Video Codecs",
			icon: "Film",
			status: "planned",
			items: [
				{
					id: "cv.video-codecs.h-264-avc",
					title: "H.264 / AVC",
					icon: "Video",
					url: "/convert/codec/h264",
					status: "planned",
				},
				{
					id: "cv.video-codecs.h-265-hevc",
					title: "H.265 / HEVC",
					icon: "Video",
					url: "/convert/codec/h265",
					status: "planned",
				},
				{
					id: "cv.video-codecs.av1-svt-av1",
					title: "AV1 (SVT-AV1)",
					icon: "Zap",
					url: "/convert/codec/av1",
					status: "planned",
				},
				{
					id: "cv.video-codecs.vp9",
					title: "VP9",
					icon: "SquarePlay",
					url: "/convert/codec/vp9",
					status: "planned",
				},
				{
					id: "cv.video-codecs.prores-422",
					title: "ProRes 422",
					icon: "Clapperboard",
					url: "/convert/codec/prores",
					status: "planned",
				},
				{
					id: "cv.video-codecs.prores-4444",
					title: "ProRes 4444",
					icon: "Clapperboard",
					url: "/convert/codec/prores4444",
					status: "planned",
				},
				{
					id: "cv.video-codecs.dnxhr-dnxhd",
					title: "DNxHR / DNxHD",
					icon: "Clapperboard",
					url: "/convert/codec/dnxhr",
					status: "planned",
				},
			],
		},
		{
			id: "cv.audio-codecs",
			title: "Audio Codecs",
			icon: "FileHeadphone",
			status: "planned",
			items: [
				{
					id: "cv.audio-codecs.aac",
					title: "AAC",
					icon: "AudioLines",
					url: "/convert/audio/aac",
					status: "planned",
				},
				{
					id: "cv.audio-codecs.mp3-lame",
					title: "MP3 (LAME)",
					icon: "Music",
					url: "/convert/audio/mp3",
					status: "planned",
				},
				{
					id: "cv.audio-codecs.flac",
					title: "FLAC",
					icon: "Disc3",
					url: "/convert/audio/flac",
					status: "planned",
				},
				{
					id: "cv.audio-codecs.wav-pcm",
					title: "WAV (PCM)",
					icon: "Activity",
					url: "/convert/audio/wav",
					status: "planned",
				},
				{
					id: "cv.audio-codecs.opus",
					title: "Opus",
					icon: "Radio",
					url: "/convert/audio/opus",
					status: "planned",
				},
				{
					id: "cv.audio-codecs.alac",
					title: "ALAC",
					icon: "FileMusic",
					url: "/convert/audio/alac",
					status: "planned",
				},
			],
		},
		{
			id: "cv.nle-presets",
			title: "NLE Presets",
			icon: "Clapperboard",
			status: "planned",
			items: [
				{
					id: "cv.nle-presets.premiere-pro",
					title: "Premiere Pro",
					icon: "Palette",
					status: "planned",
					items: [
						{
							id: "cv.nle-presets.premiere-pro.h-264-aac",
							title: "H.264 + AAC",
							icon: "Video",
							url: "/convert/preset/premiere/h264",
							status: "planned",
						},
						{
							id: "cv.nle-presets.premiere-pro.prores-422-hq",
							title: "ProRes 422 HQ",
							icon: "Clapperboard",
							url: "/convert/preset/premiere/prores-hq",
							status: "planned",
						},
						{
							id: "cv.nle-presets.premiere-pro.proxy-res",
							title: "Proxy (¼ Res)",
							icon: "Gauge",
							url: "/convert/preset/premiere/proxy",
							status: "planned",
						},
					],
				},
				{
					id: "cv.nle-presets.davinci-resolve",
					title: "DaVinci Resolve",
					icon: "Palette",
					status: "planned",
					items: [
						{
							id: "cv.nle-presets.davinci-resolve.dnxhr-hqx-10-bit",
							title: "DNxHR HQX 10-bit",
							icon: "Clapperboard",
							url: "/convert/preset/resolve/dnxhr-hqx",
							status: "planned",
						},
						{
							id: "cv.nle-presets.davinci-resolve.prores-422",
							title: "ProRes 422",
							icon: "Clapperboard",
							url: "/convert/preset/resolve/prores",
							status: "planned",
						},
						{
							id: "cv.nle-presets.davinci-resolve.h-264-high-gpu",
							title: "H.264 High GPU",
							icon: "Cpu",
							url: "/convert/preset/resolve/h264-gpu",
							status: "planned",
						},
					],
				},
				{
					id: "cv.nle-presets.final-cut-pro",
					title: "Final Cut Pro",
					icon: "Palette",
					status: "planned",
					items: [
						{
							id: "cv.nle-presets.final-cut-pro.prores-422",
							title: "ProRes 422",
							icon: "Clapperboard",
							url: "/convert/preset/fcp/prores",
							status: "planned",
						},
						{
							id: "cv.nle-presets.final-cut-pro.prores-4444",
							title: "ProRes 4444",
							icon: "Clapperboard",
							url: "/convert/preset/fcp/prores4444",
							status: "planned",
						},
						{
							id: "cv.nle-presets.final-cut-pro.hevc-hw",
							title: "HEVC HW",
							icon: "Cpu",
							url: "/convert/preset/fcp/hevc",
							status: "planned",
						},
					],
				},
				{
					id: "cv.nle-presets.after-effects",
					title: "After Effects",
					icon: "Palette",
					status: "planned",
					items: [
						{
							id: "cv.nle-presets.after-effects.prores-4444-vfx",
							title: "ProRes 4444 VFX",
							icon: "Clapperboard",
							url: "/convert/preset/ae/prores4444",
							status: "planned",
						},
						{
							id: "cv.nle-presets.after-effects.png-sequence",
							title: "PNG Sequence",
							icon: "FileImage",
							url: "/convert/preset/ae/png-seq",
							status: "planned",
						},
						{
							id: "cv.nle-presets.after-effects.exr-sequence",
							title: "EXR Sequence",
							icon: "FileImage",
							url: "/convert/preset/ae/exr-seq",
							status: "planned",
						},
					],
				},
			],
		},
		{
			id: "cv.hw-acceleration",
			title: "HW Acceleration",
			icon: "Cpu",
			status: "planned",
			items: [
				{
					id: "cv.hw-acceleration.nvenc-nvidia",
					title: "NVENC (NVIDIA)",
					icon: "Gauge",
					url: "/convert/hwaccel/nvenc",
					status: "planned",
				},
				{
					id: "cv.hw-acceleration.qsv-intel",
					title: "QSV (Intel)",
					icon: "Gauge",
					url: "/convert/hwaccel/qsv",
					status: "planned",
				},
				{
					id: "cv.hw-acceleration.vaapi-linux",
					title: "VAAPI (Linux)",
					icon: "Globe",
					url: "/convert/hwaccel/vaapi",
					status: "planned",
				},
				{
					id: "cv.hw-acceleration.videotoolbox",
					title: "VideoToolbox",
					icon: "Monitor",
					url: "/convert/hwaccel/vtb",
					status: "planned",
				},
				{
					id: "cv.hw-acceleration.amf-amd",
					title: "AMF (AMD)",
					icon: "Cpu",
					url: "/convert/hwaccel/amf",
					status: "planned",
				},
			],
		},
	],
};
