import type { NavGroup } from "./types";

export const MEDIA_GROUP: NavGroup = {
	id: "md",
	label: "Media Processing",
	items: [
		{
			id: "md.trim-cut",
			title: "Trim & Cut",
			icon: "Scissors",
			status: "planned",
			items: [
				{
					id: "md.trim-cut.lossless-trim",
					title: "Lossless Trim",
					icon: "Scissors",
					url: "/process/trim/lossless",
					status: "planned",
				},
				{
					id: "md.trim-cut.frame-accurate-cut",
					title: "Frame-Accurate Cut",
					icon: "Timer",
					url: "/process/trim/frame-accurate",
					status: "planned",
				},
				{
					id: "md.trim-cut.split-by-duration",
					title: "Split by Duration",
					icon: "Split",
					url: "/process/trim/split",
					status: "planned",
				},
			],
		},
		{
			id: "md.audio-processing",
			title: "Audio Processing",
			icon: "Volume2",
			status: "planned",
			items: [
				{
					id: "md.audio-processing.extract-track",
					title: "Extract Track",
					icon: "Music",
					url: "/process/audio/extract",
					status: "planned",
				},
				{
					id: "md.audio-processing.normalize",
					title: "Normalize",
					icon: "Activity",
					url: "/process/audio/normalize",
					status: "planned",
				},
				{
					id: "md.audio-processing.merge-tracks",
					title: "Merge Tracks",
					icon: "Disc3",
					url: "/process/audio/merge",
					status: "planned",
				},
				{
					id: "md.audio-processing.replace-audio",
					title: "Replace Audio",
					icon: "Replace",
					url: "/process/audio/replace",
					status: "planned",
				},
			],
		},
		{
			id: "md.image-frames",
			title: "Image & Frames",
			icon: "FileImage",
			status: "planned",
			items: [
				{
					id: "md.image-frames.extract-frames",
					title: "Extract Frames",
					icon: "Image",
					url: "/process/frames/extract",
					status: "planned",
				},
				{
					id: "md.image-frames.sequence-video",
					title: "Sequence → Video",
					icon: "Film",
					url: "/process/frames/sequence",
					status: "planned",
				},
				{
					id: "md.image-frames.gif-creation",
					title: "GIF Creation",
					icon: "CirclePlay",
					url: "/process/frames/gif",
					status: "planned",
				},
				{
					id: "md.image-frames.contact-sheet",
					title: "Contact Sheet",
					icon: "Grid2x2",
					url: "/process/frames/contact-sheet",
					status: "planned",
				},
			],
		},
		{
			id: "md.video-adjustments",
			title: "Video Adjustments",
			icon: "Ratio",
			status: "planned",
			items: [
				{
					id: "md.video-adjustments.scale-resize",
					title: "Scale / Resize",
					icon: "Scaling",
					url: "/process/adjust/scale",
					status: "planned",
				},
				{
					id: "md.video-adjustments.crop",
					title: "Crop",
					icon: "Crop",
					url: "/process/adjust/crop",
					status: "planned",
				},
				{
					id: "md.video-adjustments.frame-rate",
					title: "Frame Rate",
					icon: "RefreshCcw",
					url: "/process/adjust/fps",
					status: "planned",
				},
				{
					id: "md.video-adjustments.deinterlace",
					title: "Deinterlace",
					icon: "ScanLine",
					url: "/process/adjust/deinterlace",
					status: "planned",
				},
				{
					id: "md.video-adjustments.color-space",
					title: "Color Space",
					icon: "Contrast",
					url: "/process/adjust/colorspace",
					status: "planned",
				},
				{
					id: "md.video-adjustments.hdr-sdr",
					title: "HDR → SDR",
					icon: "Sun",
					url: "/process/adjust/tonemap",
					status: "planned",
				},
			],
		},
	],
};
