import type { NavGroup } from "./types";

export const YOUTUBE_GROUP: NavGroup = {
	id: "yt",
	label: "Youtube Tools",
	items: [
		{
			id: "yt.download",
			title: "Download",
			icon: "Download",
			// The branch owns the landing page at this route, so the header can
			// title it and the structure check can see the page is accounted for.
			url: "/youtube/download",
			status: "ready",
			items: [
				{
					id: "yt.download.single-video",
					title: "Single Video",
					icon: "FileVideoCamera",
					url: "/youtube/download/video#url",
					shortcut: "ytdv",
					status: "ready",
				},
				{
					id: "yt.download.playlist",
					title: "Playlist",
					icon: "ListVideo",
					url: "/youtube/download/playlist#url",
					shortcut: "ytdp",
					status: "planned",
				},
				{
					id: "yt.download.channel",
					title: "Channel",
					icon: "User",
					url: "/youtube/download/channel#url",
					shortcut: "ytdc",
					status: "planned",
				},
				{
					id: "yt.download.audio-only",
					title: "Audio Only",
					icon: "Music",
					url: "/youtube/download/audio#url",
					shortcut: "ytda",
					status: "planned",
				},
				{
					id: "yt.download.subtitles",
					title: "Subtitles",
					icon: "Captions",
					url: "/youtube/download/subtitles#url",
					shortcut: "ytds",
					status: "planned",
				},
				{
					id: "yt.download.thumbnail",
					title: "Thumbnail",
					icon: "ImageDown",
					url: "/youtube/download/thumbnail#url",
					shortcut: "ytdt",
					status: "planned",
				},
			],
		},
		{
			id: "yt.metadata",
			title: "Metadata",
			icon: "Info",
			status: "planned",
			items: [
				{
					id: "yt.metadata.video-info",
					title: "Video Info",
					icon: "CirclePlay",
					url: "/youtube/metadata/video",
					shortcut: "ytmv",
					status: "planned",
				},
				{
					id: "yt.metadata.playlist-index",
					title: "Playlist Index",
					icon: "List",
					url: "/youtube/metadata/playlist",
					shortcut: "ytmp",
					status: "planned",
				},
				{
					id: "yt.metadata.format-inspector",
					title: "Format Inspector",
					icon: "ScanLine",
					url: "/youtube/metadata/formats",
					shortcut: "ytmf",
					status: "planned",
				},
			],
		},
		{
			id: "yt.format-selection",
			title: "Format Selection",
			icon: "LayoutGrid",
			status: "planned",
			items: [
				{
					id: "yt.format-selection.best-quality",
					title: "Best Quality",
					icon: "Sparkles",
					url: "/youtube/format/best",
					status: "planned",
				},
				{
					id: "yt.format-selection.by-resolution",
					title: "By Resolution",
					icon: "Monitor",
					status: "planned",
					items: [
						{
							id: "yt.format-selection.by-resolution.4k-2160p",
							title: "4K (2160p)",
							icon: "Tv",
							url: "/youtube/format#2160p",
							shortcut: "ytf4k",
							status: "planned",
						},
						{
							id: "yt.format-selection.by-resolution.2k-1440p",
							title: "2K (1440p)",
							icon: "Tv",
							url: "/youtube/format#1440p",
							shortcut: "ytf2k",
							status: "planned",
						},
						{
							id: "yt.format-selection.by-resolution.full-hd-1080p",
							title: "Full HD (1080p)",
							icon: "Monitor",
							url: "/youtube/format#1080p",
							shortcut: "ytffhd",
							status: "planned",
						},
						{
							id: "yt.format-selection.by-resolution.hd-720p",
							title: "HD (720p)",
							icon: "Monitor",
							url: "/youtube/format#720p",
							shortcut: "ytfhd",
							status: "planned",
						},
						{
							id: "yt.format-selection.by-resolution.sd-480p",
							title: "SD (480p)",
							icon: "Monitor",
							url: "/youtube/format#480p",
							shortcut: "ytfsd",
							status: "planned",
						},
					],
				},
				{
					id: "yt.format-selection.by-codec",
					title: "By Codec",
					icon: "Film",
					status: "planned",
					items: [
						{
							id: "yt.format-selection.by-codec.av1",
							title: "AV1",
							icon: "Zap",
							url: "/youtube/format/av1",
							status: "planned",
						},
						{
							id: "yt.format-selection.by-codec.vp9",
							title: "VP9",
							icon: "SquarePlay",
							url: "/youtube/format/vp9",
							status: "planned",
						},
						{
							id: "yt.format-selection.by-codec.h-264-avc",
							title: "H.264 / AVC",
							icon: "Video",
							url: "/youtube/format/h264",
							status: "planned",
						},
					],
				},
				{
					id: "yt.format-selection.audio-formats",
					title: "Audio Formats",
					icon: "Activity",
					status: "planned",
					items: [
						{
							id: "yt.format-selection.audio-formats.opus",
							title: "Opus",
							icon: "Radio",
							url: "/youtube/format/opus",
							status: "planned",
						},
						{
							id: "yt.format-selection.audio-formats.aac",
							title: "AAC",
							icon: "AudioLines",
							url: "/youtube/format/aac",
							status: "planned",
						},
						{
							id: "yt.format-selection.audio-formats.mp3-320kbps",
							title: "MP3 320kbps",
							icon: "Music",
							url: "/youtube/format/mp3",
							status: "planned",
						},
					],
				},
			],
		},
	],
};
